### ISSUE TITLE
Change to bash

### ISSUE THREAD

**Issue by sanmadjack** [arader/collectd-plugins#1]
https://github.com/arader/collectd-plugins/blob/65d2640515fa7a60d3abe25289520b33b221131c/exec-zfs.sh#L1

needs to be bin/bash, otherwise the script only works if the system has bash running for sh.

**Comment by arader** [comment]
I don’t have bash on any of my systems, not having a properly configured `sh` shouldn’t be worked around in scripts, you should fix your system
