### ISSUE TITLE
Comparison can't handle decimal interval

### ISSUE THREAD

**Issue by sanmadjack** [arader/collectd-plugins#2]
https://github.com/arader/collectd-plugins/blob/65d2640515fa7a60d3abe25289520b33b221131c/exec-zfs.sh#L15

`if [[ $(bc <<<"300 > $INTERVAL") == "1" ]]`

**Comment by arader** [comment]
Fixed with a17ffcdc8041d91092bd2edc6c44f210d6cfb51b
